### List User
GET http://localhost:8001/user/list?offset=0&limit=20

### Get User
GET http://localhost:8001/user/1

### Create User
POST http://localhost:8001/user
Content-Type: application/json

{
  "name": "Daniel",
  "username": "daniel",
  "email": "daniel@example.com",
  "password": "senha123",
  "phone": "11999999999",
  "role": "user"
}

### Update User
PUT http://localhost:8001/user/1
Content-Type: application/json

{
  "name": "Daniel",
  "username": "daniel",
  "email": "daniel@example.com",
  "password": "senha123",
  "phone": "11999999999",
  "role": "user"
}

### Delete User
DELETE http://localhost:8001/user/1
