// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Leli2004/API_Go_biblioteca/internal/entity"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tx, input
func (_m *Repository) Create(ctx context.Context, tx *sqlx.Tx, input entity.Reservation) (context.Context, error, entity.Reservation) {
	ret := _m.Called(ctx, tx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 context.Context
	var r1 error
	var r2 entity.Reservation
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, entity.Reservation) (context.Context, error, entity.Reservation)); ok {
		return rf(ctx, tx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, entity.Reservation) context.Context); ok {
		r0 = rf(ctx, tx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, entity.Reservation) error); ok {
		r1 = rf(ctx, tx, input)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *sqlx.Tx, entity.Reservation) entity.Reservation); ok {
		r2 = rf(ctx, tx, input)
	} else {
		r2 = ret.Get(2).(entity.Reservation)
	}

	return r0, r1, r2
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - input entity.Reservation
func (_e *Repository_Expecter) Create(ctx interface{}, tx interface{}, input interface{}) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", ctx, tx, input)}
}

func (_c *Repository_Create_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, input entity.Reservation)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(entity.Reservation))
	})
	return _c
}

func (_c *Repository_Create_Call) Return(_a0 context.Context, _a1 error, _a2 entity.Reservation) *Repository_Create_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, entity.Reservation) (context.Context, error, entity.Reservation)) *Repository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveByUserAndBook provides a mock function with given fields: ctx, tx, userId, bookId
func (_m *Repository) GetActiveByUserAndBook(ctx context.Context, tx *sqlx.Tx, userId int, bookId int) (context.Context, error, entity.Reservation) {
	ret := _m.Called(ctx, tx, userId, bookId)

	if len(ret) == 0 {
		panic("no return value specified for GetActiveByUserAndBook")
	}

	var r0 context.Context
	var r1 error
	var r2 entity.Reservation
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int, int) (context.Context, error, entity.Reservation)); ok {
		return rf(ctx, tx, userId, bookId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int, int) context.Context); ok {
		r0 = rf(ctx, tx, userId, bookId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int, int) error); ok {
		r1 = rf(ctx, tx, userId, bookId)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *sqlx.Tx, int, int) entity.Reservation); ok {
		r2 = rf(ctx, tx, userId, bookId)
	} else {
		r2 = ret.Get(2).(entity.Reservation)
	}

	return r0, r1, r2
}

// Repository_GetActiveByUserAndBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveByUserAndBook'
type Repository_GetActiveByUserAndBook_Call struct {
	*mock.Call
}

// GetActiveByUserAndBook is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - userId int
//   - bookId int
func (_e *Repository_Expecter) GetActiveByUserAndBook(ctx interface{}, tx interface{}, userId interface{}, bookId interface{}) *Repository_GetActiveByUserAndBook_Call {
	return &Repository_GetActiveByUserAndBook_Call{Call: _e.mock.On("GetActiveByUserAndBook", ctx, tx, userId, bookId)}
}

func (_c *Repository_GetActiveByUserAndBook_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, userId int, bookId int)) *Repository_GetActiveByUserAndBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *Repository_GetActiveByUserAndBook_Call) Return(_a0 context.Context, _a1 error, _a2 entity.Reservation) *Repository_GetActiveByUserAndBook_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_GetActiveByUserAndBook_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, int, int) (context.Context, error, entity.Reservation)) *Repository_GetActiveByUserAndBook_Call {
	_c.Call.Return(run)
	return _c
}

// GetNextPosition provides a mock function with given fields: ctx, tx, bookId
func (_m *Repository) GetNextPosition(ctx context.Context, tx *sqlx.Tx, bookId int) (context.Context, error, int) {
	ret := _m.Called(ctx, tx, bookId)

	if len(ret) == 0 {
		panic("no return value specified for GetNextPosition")
	}

	var r0 context.Context
	var r1 error
	var r2 int
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int) (context.Context, error, int)); ok {
		return rf(ctx, tx, bookId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int) context.Context); ok {
		r0 = rf(ctx, tx, bookId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int) error); ok {
		r1 = rf(ctx, tx, bookId)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *sqlx.Tx, int) int); ok {
		r2 = rf(ctx, tx, bookId)
	} else {
		r2 = ret.Get(2).(int)
	}

	return r0, r1, r2
}

// Repository_GetNextPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNextPosition'
type Repository_GetNextPosition_Call struct {
	*mock.Call
}

// GetNextPosition is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - bookId int
func (_e *Repository_Expecter) GetNextPosition(ctx interface{}, tx interface{}, bookId interface{}) *Repository_GetNextPosition_Call {
	return &Repository_GetNextPosition_Call{Call: _e.mock.On("GetNextPosition", ctx, tx, bookId)}
}

func (_c *Repository_GetNextPosition_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, bookId int)) *Repository_GetNextPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(int))
	})
	return _c
}

func (_c *Repository_GetNextPosition_Call) Return(_a0 context.Context, _a1 error, _a2 int) *Repository_GetNextPosition_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_GetNextPosition_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, int) (context.Context, error, int)) *Repository_GetNextPosition_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
