// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Leli2004/API_Go_biblioteca/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

type UseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UseCase) EXPECT() *UseCase_Expecter {
	return &UseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, input
func (_m *UseCase) Create(ctx context.Context, input entity.Reservation) (context.Context, error, entity.Reservation) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 context.Context
	var r1 error
	var r2 entity.Reservation
	if rf, ok := ret.Get(0).(func(context.Context, entity.Reservation) (context.Context, error, entity.Reservation)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Reservation) context.Context); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Reservation) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.Reservation) entity.Reservation); ok {
		r2 = rf(ctx, input)
	} else {
		r2 = ret.Get(2).(entity.Reservation)
	}

	return r0, r1, r2
}

// UseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input entity.Reservation
func (_e *UseCase_Expecter) Create(ctx interface{}, input interface{}) *UseCase_Create_Call {
	return &UseCase_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *UseCase_Create_Call) Run(run func(ctx context.Context, input entity.Reservation)) *UseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Reservation))
	})
	return _c
}

func (_c *UseCase_Create_Call) Return(_a0 context.Context, _a1 error, _a2 entity.Reservation) *UseCase_Create_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UseCase_Create_Call) RunAndReturn(run func(context.Context, entity.Reservation) (context.Context, error, entity.Reservation)) *UseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
