package helpers

// ERROR RESPONSE HTTP
const (
	REPONSE_HTTP_BAD_REQUEST = 400
	REPONSE_HTTP_OK          = 200
)

// BACKGROUND JOBS AND DEFAULT BUSINESS VALUES
const (
	TIME_CHECK_FINE_MINUTES = 60
	DEFAULT_FINE_AMOUNT     = 10.00
	DEFAULT_FINE_REASON     = "Empréstimo em atraso"
)
