// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Leli2004/API_Go_biblioteca/internal/entity"
	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

type UseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UseCase) EXPECT() *UseCase_Expecter {
	return &UseCase_Expecter{mock: &_m.Mock}
}

// Login provides a mock function with given fields: ctx, input
func (_m *UseCase) Login(ctx context.Context, input entity.LoginRequest) (context.Context, error, entity.LoginResponse) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 context.Context
	var r1 error
	var r2 entity.LoginResponse
	if rf, ok := ret.Get(0).(func(context.Context, entity.LoginRequest) (context.Context, error, entity.LoginResponse)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.LoginRequest) context.Context); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.LoginRequest) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.LoginRequest) entity.LoginResponse); ok {
		r2 = rf(ctx, input)
	} else {
		r2 = ret.Get(2).(entity.LoginResponse)
	}

	return r0, r1, r2
}

// UseCase_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type UseCase_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - input entity.LoginRequest
func (_e *UseCase_Expecter) Login(ctx interface{}, input interface{}) *UseCase_Login_Call {
	return &UseCase_Login_Call{Call: _e.mock.On("Login", ctx, input)}
}

func (_c *UseCase_Login_Call) Run(run func(ctx context.Context, input entity.LoginRequest)) *UseCase_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.LoginRequest))
	})
	return _c
}

func (_c *UseCase_Login_Call) Return(_a0 context.Context, _a1 error, _a2 entity.LoginResponse) *UseCase_Login_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UseCase_Login_Call) RunAndReturn(run func(context.Context, entity.LoginRequest) (context.Context, error, entity.LoginResponse)) *UseCase_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Me provides a mock function with given fields: ctx, userID
func (_m *UseCase) Me(ctx context.Context, userID int) (context.Context, error, entity.AuthUser) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Me")
	}

	var r0 context.Context
	var r1 error
	var r2 entity.AuthUser
	if rf, ok := ret.Get(0).(func(context.Context, int) (context.Context, error, entity.AuthUser)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) context.Context); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) entity.AuthUser); ok {
		r2 = rf(ctx, userID)
	} else {
		r2 = ret.Get(2).(entity.AuthUser)
	}

	return r0, r1, r2
}

// UseCase_Me_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Me'
type UseCase_Me_Call struct {
	*mock.Call
}

// Me is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int
func (_e *UseCase_Expecter) Me(ctx interface{}, userID interface{}) *UseCase_Me_Call {
	return &UseCase_Me_Call{Call: _e.mock.On("Me", ctx, userID)}
}

func (_c *UseCase_Me_Call) Run(run func(ctx context.Context, userID int)) *UseCase_Me_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *UseCase_Me_Call) Return(_a0 context.Context, _a1 error, _a2 entity.AuthUser) *UseCase_Me_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UseCase_Me_Call) RunAndReturn(run func(context.Context, int) (context.Context, error, entity.AuthUser)) *UseCase_Me_Call {
	_c.Call.Return(run)
	return _c
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
