
api:
  port: "8001"

database:
  host: "localhost"
  port: "5433"
  user: "postgres"
  pass: "1234"
  name: "postgres"

auth:
  jwt_secret: "develop-secret"
  jwt_issuer: "biblioteca-api"
  jwt_expire_hours: 24
