// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Leli2004/API_Go_biblioteca/internal/entity"

	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

type UseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UseCase) EXPECT() *UseCase_Expecter {
	return &UseCase_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, input
func (_m *UseCase) Create(ctx context.Context, input entity.Loan) (context.Context, error, entity.Loan) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 context.Context
	var r1 error
	var r2 entity.Loan
	if rf, ok := ret.Get(0).(func(context.Context, entity.Loan) (context.Context, error, entity.Loan)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.Loan) context.Context); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.Loan) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.Loan) entity.Loan); ok {
		r2 = rf(ctx, input)
	} else {
		r2 = ret.Get(2).(entity.Loan)
	}

	return r0, r1, r2
}

// UseCase_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UseCase_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - input entity.Loan
func (_e *UseCase_Expecter) Create(ctx interface{}, input interface{}) *UseCase_Create_Call {
	return &UseCase_Create_Call{Call: _e.mock.On("Create", ctx, input)}
}

func (_c *UseCase_Create_Call) Run(run func(ctx context.Context, input entity.Loan)) *UseCase_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.Loan))
	})
	return _c
}

func (_c *UseCase_Create_Call) Return(_a0 context.Context, _a1 error, _a2 entity.Loan) *UseCase_Create_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UseCase_Create_Call) RunAndReturn(run func(context.Context, entity.Loan) (context.Context, error, entity.Loan)) *UseCase_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *UseCase) Delete(ctx context.Context, id int) (context.Context, error, entity.Loan) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 context.Context
	var r1 error
	var r2 entity.Loan
	if rf, ok := ret.Get(0).(func(context.Context, int) (context.Context, error, entity.Loan)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) context.Context); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) entity.Loan); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Get(2).(entity.Loan)
	}

	return r0, r1, r2
}

// UseCase_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UseCase_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *UseCase_Expecter) Delete(ctx interface{}, id interface{}) *UseCase_Delete_Call {
	return &UseCase_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *UseCase_Delete_Call) Run(run func(ctx context.Context, id int)) *UseCase_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *UseCase_Delete_Call) Return(_a0 context.Context, _a1 error, _a2 entity.Loan) *UseCase_Delete_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UseCase_Delete_Call) RunAndReturn(run func(context.Context, int) (context.Context, error, entity.Loan)) *UseCase_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *UseCase) Get(ctx context.Context, id int) (context.Context, error, entity.Loan) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 context.Context
	var r1 error
	var r2 entity.Loan
	if rf, ok := ret.Get(0).(func(context.Context, int) (context.Context, error, entity.Loan)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) context.Context); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int) entity.Loan); ok {
		r2 = rf(ctx, id)
	} else {
		r2 = ret.Get(2).(entity.Loan)
	}

	return r0, r1, r2
}

// UseCase_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UseCase_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *UseCase_Expecter) Get(ctx interface{}, id interface{}) *UseCase_Get_Call {
	return &UseCase_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *UseCase_Get_Call) Run(run func(ctx context.Context, id int)) *UseCase_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *UseCase_Get_Call) Return(_a0 context.Context, _a1 error, _a2 entity.Loan) *UseCase_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UseCase_Get_Call) RunAndReturn(run func(context.Context, int) (context.Context, error, entity.Loan)) *UseCase_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, input
func (_m *UseCase) List(ctx context.Context, input entity.LoanFilters) (context.Context, error, entity.LoanList) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 context.Context
	var r1 error
	var r2 entity.LoanList
	if rf, ok := ret.Get(0).(func(context.Context, entity.LoanFilters) (context.Context, error, entity.LoanList)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, entity.LoanFilters) context.Context); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, entity.LoanFilters) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(context.Context, entity.LoanFilters) entity.LoanList); ok {
		r2 = rf(ctx, input)
	} else {
		r2 = ret.Get(2).(entity.LoanList)
	}

	return r0, r1, r2
}

// UseCase_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type UseCase_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - input entity.LoanFilters
func (_e *UseCase_Expecter) List(ctx interface{}, input interface{}) *UseCase_List_Call {
	return &UseCase_List_Call{Call: _e.mock.On("List", ctx, input)}
}

func (_c *UseCase_List_Call) Run(run func(ctx context.Context, input entity.LoanFilters)) *UseCase_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(entity.LoanFilters))
	})
	return _c
}

func (_c *UseCase_List_Call) Return(_a0 context.Context, _a1 error, _a2 entity.LoanList) *UseCase_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UseCase_List_Call) RunAndReturn(run func(context.Context, entity.LoanFilters) (context.Context, error, entity.LoanList)) *UseCase_List_Call {
	_c.Call.Return(run)
	return _c
}

// Return provides a mock function with given fields: ctx, loanId, returnedAt
func (_m *UseCase) Return(ctx context.Context, loanId int, returnedAt *string) (context.Context, error, entity.Loan) {
	ret := _m.Called(ctx, loanId, returnedAt)

	if len(ret) == 0 {
		panic("no return value specified for Return")
	}

	var r0 context.Context
	var r1 error
	var r2 entity.Loan
	if rf, ok := ret.Get(0).(func(context.Context, int, *string) (context.Context, error, entity.Loan)); ok {
		return rf(ctx, loanId, returnedAt)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, *string) context.Context); ok {
		r0 = rf(ctx, loanId, returnedAt)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, *string) error); ok {
		r1 = rf(ctx, loanId, returnedAt)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(context.Context, int, *string) entity.Loan); ok {
		r2 = rf(ctx, loanId, returnedAt)
	} else {
		r2 = ret.Get(2).(entity.Loan)
	}

	return r0, r1, r2
}

// UseCase_Return_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Return'
type UseCase_Return_Call struct {
	*mock.Call
}

// Return is a helper method to define mock.On call
//   - ctx context.Context
//   - loanId int
//   - returnedAt *string
func (_e *UseCase_Expecter) Return(ctx interface{}, loanId interface{}, returnedAt interface{}) *UseCase_Return_Call {
	return &UseCase_Return_Call{Call: _e.mock.On("Return", ctx, loanId, returnedAt)}
}

func (_c *UseCase_Return_Call) Run(run func(ctx context.Context, loanId int, returnedAt *string)) *UseCase_Return_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(*string))
	})
	return _c
}

func (_c *UseCase_Return_Call) Return(_a0 context.Context, _a1 error, _a2 entity.Loan) *UseCase_Return_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *UseCase_Return_Call) RunAndReturn(run func(context.Context, int, *string) (context.Context, error, entity.Loan)) *UseCase_Return_Call {
	_c.Call.Return(run)
	return _c
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
