// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "github.com/Leli2004/API_Go_biblioteca/internal/entity"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, tx, input
func (_m *Repository) Create(ctx context.Context, tx *sqlx.Tx, input entity.Publisher) (context.Context, error, entity.Publisher) {
	ret := _m.Called(ctx, tx, input)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 context.Context
	var r1 error
	var r2 entity.Publisher
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, entity.Publisher) (context.Context, error, entity.Publisher)); ok {
		return rf(ctx, tx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, entity.Publisher) context.Context); ok {
		r0 = rf(ctx, tx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, entity.Publisher) error); ok {
		r1 = rf(ctx, tx, input)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *sqlx.Tx, entity.Publisher) entity.Publisher); ok {
		r2 = rf(ctx, tx, input)
	} else {
		r2 = ret.Get(2).(entity.Publisher)
	}

	return r0, r1, r2
}

// Repository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type Repository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - input entity.Publisher
func (_e *Repository_Expecter) Create(ctx interface{}, tx interface{}, input interface{}) *Repository_Create_Call {
	return &Repository_Create_Call{Call: _e.mock.On("Create", ctx, tx, input)}
}

func (_c *Repository_Create_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, input entity.Publisher)) *Repository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(entity.Publisher))
	})
	return _c
}

func (_c *Repository_Create_Call) Return(_a0 context.Context, _a1 error, _a2 entity.Publisher) *Repository_Create_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_Create_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, entity.Publisher) (context.Context, error, entity.Publisher)) *Repository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, tx, id
func (_m *Repository) Delete(ctx context.Context, tx *sqlx.Tx, id int) (context.Context, error) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 context.Context
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int) (context.Context, error)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int) context.Context); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type Repository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - id int
func (_e *Repository_Expecter) Delete(ctx interface{}, tx interface{}, id interface{}) *Repository_Delete_Call {
	return &Repository_Delete_Call{Call: _e.mock.On("Delete", ctx, tx, id)}
}

func (_c *Repository_Delete_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, id int)) *Repository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(int))
	})
	return _c
}

func (_c *Repository_Delete_Call) Return(_a0 context.Context, _a1 error) *Repository_Delete_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Delete_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, int) (context.Context, error)) *Repository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, tx, id
func (_m *Repository) Get(ctx context.Context, tx *sqlx.Tx, id int) (context.Context, error, entity.Publisher) {
	ret := _m.Called(ctx, tx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 context.Context
	var r1 error
	var r2 entity.Publisher
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int) (context.Context, error, entity.Publisher)); ok {
		return rf(ctx, tx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int) context.Context); ok {
		r0 = rf(ctx, tx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int) error); ok {
		r1 = rf(ctx, tx, id)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *sqlx.Tx, int) entity.Publisher); ok {
		r2 = rf(ctx, tx, id)
	} else {
		r2 = ret.Get(2).(entity.Publisher)
	}

	return r0, r1, r2
}

// Repository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Repository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - id int
func (_e *Repository_Expecter) Get(ctx interface{}, tx interface{}, id interface{}) *Repository_Get_Call {
	return &Repository_Get_Call{Call: _e.mock.On("Get", ctx, tx, id)}
}

func (_c *Repository_Get_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, id int)) *Repository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(int))
	})
	return _c
}

func (_c *Repository_Get_Call) Return(_a0 context.Context, _a1 error, _a2 entity.Publisher) *Repository_Get_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_Get_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, int) (context.Context, error, entity.Publisher)) *Repository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, tx, input
func (_m *Repository) List(ctx context.Context, tx *sqlx.Tx, input entity.PublisherFilters) (context.Context, error, entity.PublisherList) {
	ret := _m.Called(ctx, tx, input)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 context.Context
	var r1 error
	var r2 entity.PublisherList
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, entity.PublisherFilters) (context.Context, error, entity.PublisherList)); ok {
		return rf(ctx, tx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, entity.PublisherFilters) context.Context); ok {
		r0 = rf(ctx, tx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, entity.PublisherFilters) error); ok {
		r1 = rf(ctx, tx, input)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *sqlx.Tx, entity.PublisherFilters) entity.PublisherList); ok {
		r2 = rf(ctx, tx, input)
	} else {
		r2 = ret.Get(2).(entity.PublisherList)
	}

	return r0, r1, r2
}

// Repository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type Repository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - input entity.PublisherFilters
func (_e *Repository_Expecter) List(ctx interface{}, tx interface{}, input interface{}) *Repository_List_Call {
	return &Repository_List_Call{Call: _e.mock.On("List", ctx, tx, input)}
}

func (_c *Repository_List_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, input entity.PublisherFilters)) *Repository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(entity.PublisherFilters))
	})
	return _c
}

func (_c *Repository_List_Call) Return(_a0 context.Context, _a1 error, _a2 entity.PublisherList) *Repository_List_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_List_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, entity.PublisherFilters) (context.Context, error, entity.PublisherList)) *Repository_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, tx, id, input
func (_m *Repository) Update(ctx context.Context, tx *sqlx.Tx, id int, input entity.Publisher) (context.Context, error, entity.Publisher) {
	ret := _m.Called(ctx, tx, id, input)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 context.Context
	var r1 error
	var r2 entity.Publisher
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int, entity.Publisher) (context.Context, error, entity.Publisher)); ok {
		return rf(ctx, tx, id, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int, entity.Publisher) context.Context); ok {
		r0 = rf(ctx, tx, id, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(context.Context)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int, entity.Publisher) error); ok {
		r1 = rf(ctx, tx, id, input)
	} else {
		r1 = ret.Error(1)
	}

	if rf, ok := ret.Get(2).(func(context.Context, *sqlx.Tx, int, entity.Publisher) entity.Publisher); ok {
		r2 = rf(ctx, tx, id, input)
	} else {
		r2 = ret.Get(2).(entity.Publisher)
	}

	return r0, r1, r2
}

// Repository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type Repository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *sqlx.Tx
//   - id int
//   - input entity.Publisher
func (_e *Repository_Expecter) Update(ctx interface{}, tx interface{}, id interface{}, input interface{}) *Repository_Update_Call {
	return &Repository_Update_Call{Call: _e.mock.On("Update", ctx, tx, id, input)}
}

func (_c *Repository_Update_Call) Run(run func(ctx context.Context, tx *sqlx.Tx, id int, input entity.Publisher)) *Repository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*sqlx.Tx), args[2].(int), args[3].(entity.Publisher))
	})
	return _c
}

func (_c *Repository_Update_Call) Return(_a0 context.Context, _a1 error, _a2 entity.Publisher) *Repository_Update_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *Repository_Update_Call) RunAndReturn(run func(context.Context, *sqlx.Tx, int, entity.Publisher) (context.Context, error, entity.Publisher)) *Repository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
