
### Login
POST http://localhost:8001/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "senha123"
}

### Dados do usuário autenticado
GET http://localhost:8001/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0LCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwiaXNzIjoiYmlibGlvdGVjYS1hcGkiLCJzdWIiOiI0IiwiZXhwIjoxNzg0OTI5MDIzLCJuYmYiOjE3ODQ4NDI2MjMsImlhdCI6MTc4NDg0MjYyM30.I4431innvyOXO78fUSRhOxrjIYj_fXAIpHui8SM4VbI
